# Generated by Django 3.1.4 on 2021-01-03 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('snippet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language', to='snippets.snippet')),
            ],
        ),
    ]
