# Generated by Django 3.1.4 on 2021-01-03 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='snippet',
        ),
    ]
